package com.naruto.mekvahandelivery.help_and_support;

import android.os.Bundle;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.naruto.mekvahandelivery.R;

import java.util.ArrayList;

public class Privacy_policy extends AppCompatActivity {

    private RecyclerView mrecyclerView;
    private RecyclerView.Adapter madapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_privacy_policy);

        ArrayList<PrivacyData> list = new ArrayList<>();

        mrecyclerView = findViewById(R.id.privacyRecycler);
        RecyclerView.LayoutManager layoutManager = new LinearLayoutManager(this);
        mrecyclerView.setLayoutManager(layoutManager);

        madapter = new PrivacyPolicyAdapter(this,list);
        mrecyclerView.setAdapter(madapter);

        list.add(new PrivacyData("PRIVACY POLICY\n",1));

        list.add(new PrivacyData("1.Background\n",2));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("1. This document is an electronic record in terms of (i) Information Technology Act, 2000; (ii) the rules framed their under as applicable; and (iii) the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("2. This Privacy Policy (“Privacy Policy”) is published in accordance with: (i) Section 43A of the Information Technology Act, 2000; (ii) Regulation 4 of the Information Technology (Reasonable security practices and procedures and sensitive personal information) Rules, 2011 (“SPI Rules”); and (iii) Regulation 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, that require publishing the privacy policy that is applicable in relation to the access or usage of mekvahan (“Web application/Website”) and http://mekvahan.com/(“Website”) together referred to as “Platform”.",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("3. The Platform is owned, registered and operated by Udyamat Ma Viramasva Private Limited (\"Company\"), a private limited company, incorporated under the provisions of the Companies Act, 2013, and having its principal place of business at Aya Nagar, delhi.",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("4. This Privacy Policy covers: (i) the type of information collected from the Registered Users (as defined below) through the Platform including sensitive personal data or information; (ii) the purpose, means and modes of usage of such information; and (iii) how and to whom such information which has been collected will be disclosed.",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("5. For the purpose of this Privacy Policy, wherever the context so requires “Your” or “User” shall mean any natural person who uses the Website for availing Services. The terms “We”, “Us”, “Our” shall mean the Company, its employees, and authorised agents that perform any services on the Company’s behalf.",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("6. We reserve the right to make changes to this Privacy Policy at any time. Any such modifications will become effective immediately upon posting to the Platform and your continued use of the Platform, and/or the Services constitutes your consent to such modifications. If you object to any changes, you may terminate your account. You agree to periodically review the current version of the Privacy Policy as posted on the Platform.",3));

        list.add(new PrivacyData("\n2. Services\n",2));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("1. We are service aggregators and through our Platform, we enable the User(s) to receive car related repairs, services and maintenance and also roadside assistance including quick check-up, key lock- out, car servicing etc.(”Services”), from third party workshops and their authorized personnel, under agreement with Us (“Service Provider”) on a real time basis. These Services are made available to You for Your personal, non-commercial use.",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("2. All the other defined terms shall have the same meaning as provided for under the Terms of Use http://mekvahan.com/terms.php published on this Platform",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("\n3. Type of information collected from the User(s)\n",2));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("1. For the purpose of this Privacy Policy, “personal information” as defined under Section 2(i) of the SPI Rules means, any information that relates to a natural person, which, either directly or indirectly, in combination with other information available or likely to be available with a body corporate, is capable of identifying such person.\n",3));

        list.add(new PrivacyData("2. “Sensitive personal information” as defined under Section 3 of the SPI Rules means such personal information which consists of information relating to:",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("i. password;\n",4));

        list.add(new PrivacyData("ii. financial information such as Bank account or credit card or debit card or other payment instrument details;",4));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("iii. physical, physiological and mental health condition;\n",4));

        list.add(new PrivacyData("iv. sexual orientation;\n",4));

        list.add(new PrivacyData("v. medical records and history;\n",4));

        list.add(new PrivacyData("vi. biometric information;\n",4));

        list.add(new PrivacyData("vii. any detail relating to the above clauses as provided to body corporate for providing service; and",4));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("viii. any of the information received under above clauses by body corporate for processing, stored or processed under lawful contract or otherwise",4));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("3. We require Users who visit the Platform or avail our service through the Platform to provide us with the following information:",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("i. Name of the User;\n",4));

        list.add(new PrivacyData("ii. E-mail Address;\n",4));

        list.add(new PrivacyData("iii. Phone Number;\n",4));

        list.add(new PrivacyData("iv. Credit card or debit card or any other such payment information which is required for payment purposes;",4));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("v. Information pertaining to your vehicle;\n",4));

        list.add(new PrivacyData("vi. Other such information  may be required at the time of availing the Services through the Platform.",4));

        list.add(new PrivacyData("\n3. How the collected information will be used\n",2));

        list.add(new PrivacyData("1. The information collected by Us, shall be used in the manner described below:",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("i. User name: The user name shall be used to address the User and to customize the Services availed by the user through the Platform, and to personalize all communications that are sent to the User by Us.",4));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("ii. E-mail Address: Your Email address will be used to communicate:",4));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("a. Service messages from time to time; and\n",5));

        list.add(new PrivacyData("b. Feedback from the User regarding the Services provided by the Service Provider;\n",5));

        list.add(new PrivacyData("c. Marketing emails; and\n",5));

        list.add(new PrivacyData("d. Any other such communication with the User\n",5));

        list.add(new PrivacyData("2. Phone Number: Phone number will be an alternative method to contact the User, for any matter related to the access of the Platform or the Services through the Platform, including but not limited to sending promotional and transactional messages.",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("3. Credit Card/Debit Card or any other such payment information: Credit Card/Debit Card or any other such payment information is used for charging the User for availing Services through the Platform.",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("4. Vehicle Information: Vehicle Information shall be used to identify the vehicle and provide appropriate Services as requested by the User.",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("5. In order to improve the quality of our Services, we may ask you to provide us with information regarding your experiences with the Service Provider and/or your experiences on the Platform. Users have the option of choosing not to provide us with this information.",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("\n4. Disclosure of Personal Information\n",2));

        list.add(new PrivacyData("1. All financial information that is collected through the Platform is used solely to enable the User to make payments for the Services availed through the Platform, and is not used for marketing or promotional purposes. Towards this end, we disclose such information to a third-party intermediary, for the sole purpose of processing the payments made by the User on the Platform.",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("2. We may also disclose certain information to third parties solely to help diagnose technical problems, to administer the Platform, and improve the quality of the Services provided by us.",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("3. We reserve the right to disclose any personal information as required by law and when we believe, at our sole discretion that disclosure is necessary to protect our rights, protect someone from injury and/or to comply with a judicial proceeding, court order, or legal process served on our Platform.",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("\n5. Cookies\n",2));

        list.add(new PrivacyData("1. The Platform uses temporary cookies, which are files that your web browser puts on your system when you visit a website, to store certain information that is not sensitive personal information. The information collected through these cookies is used by us for the technical administration of the Platform, research and development, and to improve the quality of our Platform.",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("2. We may use third party cookies to track visitor behaviour and to improve the quality of our services. However, such cookies will not store any kind of personal information, nor will such information be disclosed to any third party.",49));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("3. These cookies are intended to be automatically cleared or deleted when the User quits the browser application. You are encouraged to use the “clear cookies” functionality of your browser to ensure such clearing / deletion, since it is impossible for us to guarantee, predict or provide for the behaviour of your system.\n",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("4. The information we collect with cookies is not sold, rented, or shared with any third parties, other than for internal Platform development and maintenance.",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("\n6. Third Party Links\n",2));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("1. We may provide links to websites for the convenience and information of Users. These websites may not be owned, controlled, or operated by Us. In those cases, We cannot control how information collected by those websites will be used, shared, or secured. If the User visits linked sites, We strongly recommend that the User reviews the privacy notices or policies posted at those sites. We are not responsible for the content of linked sites, the User’s use of them, or the information practices of their operators.\n",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("\n7. Advertisement Links\n",2));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("1. The Platform may contain links to various advertisements (“Advertisement Site”). The Advertisement Site is not under the control of the Platform. We are not responsible for the content on any Advertisement Site, including, without limitation to, any link contained in the Advertisement Site, or any changes or updates to the same.\n",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("2. These Advertisement Site(s) shall be construed to be Linked Sites (as mentioned above) and the provisions of Clause 7 above shall apply for Advertisement Site(s)\n",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("\n8. Security Procedures\n",2));

        list.add(new PrivacyData("1. We have implemented industry standard security policies, rules and technical measures, to protect any kind of personal sensitive information that we have under our control from unauthorized access, improper use or disclosure, unauthorized modification and unlawful destruction or accidental loss.\n",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("\n9. Retention of Information\n",2));

        list.add(new PrivacyData("1. We retain any personal information that you may have provided to us, for as long as you engaged our services, and for a reasonable time thereafter.\n",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("\n9. Choice/Opt-Out\n",2));

        list.add(new PrivacyData("1. If the User wishes to opt- out of receiving non-essential (promotional, marketing-related) communications from Us, after setting up an account, they may choose to do so. Further, if a User wishes to remove all their contact information from the Platform, they can do so by opting out of the Platform and uninstalling the Platform.\n",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("\n10. Governing Law\n",2));

        list.add(new PrivacyData("1. Privacy Policy shall be governed by and constructed in accordance with the Applicable Law without reference to conflict of laws and principles. The courts in New Delhi, shall have the exclusive jurisdiction to determine any disputes arising in relation to, or under, this Privacy Policy.\n",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("\n11. Grievance Officer\n",2));

        list.add(new PrivacyData("1. In accordance with Information Technology Act 2000 and rules made there under, name and contact details of the Grievance Officer are provided below:\n",3));

        list.add(new PrivacyData("",000));

        list.add(new PrivacyData("Attention: Sanjeev maurya, Head of Operations.\n" +
                "email: coo@mekvahan.com\n",2));


    }
}
